Better experience using the install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,32 @@
 #!/bin/bash
 
-if [ -d "${HOME}/dotfiles" ]; then
-  echo "dotfiles already installed!"
-  exit 0
+set -euo pipefail
+
+echo ""
+echo "Installing Aerz's dotfiles"
+echo "##########################################################################"
+echo ""
+
+dotfiles_path="${HOME}/dotfiles"
+
+if [ -d "$dotfiles_path" ]; then
+  echo "dotfiles folder already exist!"
+  echo "delete the folder and run the command again"
+  echo ""
+  exit 1
 fi
 
-git clone https://github.com/aerz/dotfiles.git "${HOME}/dotfiles"
+git clone https://github.com/aerz/dotfiles.git "$dotfiles_path"
 
-ln -sv "${HOME}/dotfiles/dotfiles" "/usr/local/bin/dot"
+sudo ln -sfv "${dotfiles_path}/bin/dot" "/usr/local/bin/dot"
 
+if [ -z "$(ls -la /usr/local/bin | grep -w 'dot')" ]; then
+  echo ""
+  echo "Error: dot command was not installed, try to install it manually..."
+  exit 1
+fi
+
+echo "##########################################################################"
+echo "dotfiles installed successfully"
+echo ""
 echo "Type 'dot' on your terminal to start using the dotfiles!"
