Rofi: roblue script now toggle connections * Create a rofi fork theme for roblue * Remove old bluetooth keyboard testing script * Change shortcuts to manage the bluetooth

diff --git a/config/rofi/scripts/roblue b/config/rofi/scripts/roblue
--- a/config/rofi/scripts/roblue
+++ b/config/rofi/scripts/roblue
@@ -8,57 +8,119 @@
 #
 
 # ---
+# Config
+# ---
 
-# Rofi options
+# Rofi Options
 ropts=(
     "-i"
     "-matching fuzzy"
     "-dmenu"
-    "-theme ~/.config/rofi/themes/notifications.rasi"
+    "-theme ~/.config/rofi/themes/roblue.rasi"
 )
 
 # ---
 
-show_help() {
-    echo
-    echo "roblue - Bluetooth common actions using Rofi as interface"
-    echo
-    echo "usage: roblue <command>"
-    echo
-    echo "Commands:"
-    echo "  help                    Display this message"
-    echo "  connect                 Connect a paired device"
+help() {
+    echo '
+roblue - Bluetooth common actions using Rofi as interface
+
+Usage:
+  roblue <menu>
+  roblue <command>
+
+Menus:
+  paired                  Toggle connections of paired devices
+
+Commands:
+  help                    Display this message
+    '
     exit 0
 }
 
-show_cmd_err() {
-    echo "error: No command specified or no exists"
-    echo
-    echo "Use 'roblue help' to display the help message"
+err_unkown_cmd() {
+    echo "error: No command exists
+
+Use 'roblue help' to display the help message
+    "
     exit 1
 }
 
-open_paired_connect_menu() {
-    local title=" Connect:"
-    local devices="$1"
-    local device_name="$(echo -e "$devices" | cut -d " " -f 3- | rofi ${ropts[@]} -p "$title")"
+err_no_cmd() {
+    echo "error: No command or menu provided
 
-    echo -e "$devices" | grep -w "$device_name"
+Use 'roblue help' to display the help message
+    "
+    exit 1
+}
+
+err_no_dev() {
+    echo "error: No device selected, nothing to do"
+    exit 1
 }
 
 get_mac_address() {
-    local device="$1"
+    local dev="$1"
 
-    echo "$device" | cut -d " " -f 2
+    echo "$dev" | cut -d " " -f 2
 }
 
-case $1 in
-    connect)
-        device="$(open_paired_connect_menu "$(bluetoothctl paired-devices)")"
-        [ -z "$device" ] && echo "No device selected" && exit 1
+toggle_conn_paired_dev() {
+    local mac="$1"
+    local conn="$(bluetoothctl info "$mac" | grep 'Connected: yes')"
 
-        bluetoothctl connect "$(get_mac_address "$device")"
+    case $conn in
+        *yes)   bluetoothctl disconnect "$mac"  ;;
+        *)      bluetoothctl connect    "$mac"  ;;
+    esac
+}
+
+list_paired_devices() {
+    bluetoothctl paired-devices | cut -d " " -f 2 | xargs -I{} bluetoothctl info {} | \
+    awk '
+        /Name: / {
+            name = substr($0, index($0, $2))
+        }
+
+        /Connected: / {
+            connected = $2
+            print (connected == "yes") ? " " name : name
+        }
+    '
+}
+
+open_paired_devices_menu() {
+    local title=" Paired devices:"
+    local dev="$(list_paired_devices | rofi ${ropts[@]} -p "$title" | sed 's/^ //')"
+
+    bluetoothctl paired-devices | grep -w "$dev"
+}
+
+open_power_off_suggestions_menu() {
+    local title=" Bluetooth off:"
+    local action="$(printf "%s\n" "Turn on" "Close" | rofi ${ropts[@]} -lines 2 -p "$title")"
+
+    case $action in
+        "Turn on")  bluetoothctl power on && sleep .5   ;;
+        *)          exit 1                              ;;
+    esac
+}
+
+is_power_off() {
+    bluetoothctl show | grep -q 'Powered: no'
+}
+
+[ $# -eq 0 ] && err_no_cmd
+
+case $1 in
+    paired)
+        is_power_off && open_power_off_suggestions_menu
+
+        dev="$(open_paired_devices_menu)"
+        [ -z "$dev" ] && err_no_dev
+
+        toggle_conn_paired_dev "$(get_mac_address "$dev")"
     ;;
-    help)   show_help       ;;
-    *)      show_cmd_err    ;;
+    help)   help       ;;
+    *)      err_unkown_cmd    ;;
 esac
